dataset:
  ff_path: "/content/TEP_FaultFree_Training.RData"
  ft_path: "/content/TEP_Faulty_Training.RData"

data_windowing:
  window_size: 100
  stride: 5
  post_fault_start: 100         
  train_runs_start: 1
  train_runs_end: 50
  test_runs_start: 50
  test_runs_end: 63

training:
  epochs: 100
  batch:
    train: 128
    val: 256
    test: 256
  num_workers: 2
  seed: 42

model:
  s: 16.0
  m: 0.15
  margin_type: "arc"
  per_class_margin_overrides:
    "0": 0.28
    "15": 0.28
  center_momentum: 0.95
  center_sep_K: 3
  center_sep_margin: 0.28
  center_pull_weights:
    "0": 2.5
    "15": 3.0
